# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1019, 367)
        MainWindow.setMinimumSize(QtCore.QSize(1019, 367))
        MainWindow.setMaximumSize(QtCore.QSize(1019, 367))
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 1, 1, 1)
        self.t1_out = QtWidgets.QTextEdit(self.tab)
        self.t1_out.setReadOnly(True)
        self.t1_out.setObjectName("t1_out")
        self.gridLayout.addWidget(self.t1_out, 3, 3, 5, 1)
        self.t1_calc = QtWidgets.QPushButton(self.tab)
        self.t1_calc.setAutoDefault(False)
        self.t1_calc.setDefault(False)
        self.t1_calc.setFlat(False)
        self.t1_calc.setObjectName("t1_calc")
        self.gridLayout.addWidget(self.t1_calc, 8, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        self.t1_m = QtWidgets.QSpinBox(self.tab)
        self.t1_m.setMaximum(9999)
        self.t1_m.setObjectName("t1_m")
        self.gridLayout.addWidget(self.t1_m, 5, 2, 1, 1)
        self.t1_m2 = QtWidgets.QSpinBox(self.tab)
        self.t1_m2.setMaximum(9999)
        self.t1_m2.setObjectName("t1_m2")
        self.gridLayout.addWidget(self.t1_m2, 7, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 8, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("img/ber2.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 45))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("img/ber.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 1, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 1)
        self.t1_m1 = QtWidgets.QSpinBox(self.tab)
        self.t1_m1.setMaximum(9999)
        self.t1_m1.setObjectName("t1_m1")
        self.gridLayout.addWidget(self.t1_m1, 6, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 4, 1, 1)
        self.t1_n = QtWidgets.QSpinBox(self.tab)
        self.t1_n.setMaximum(9999)
        self.t1_n.setObjectName("t1_n")
        self.gridLayout.addWidget(self.t1_n, 4, 2, 1, 1)
        self.t1_p = QtWidgets.QDoubleSpinBox(self.tab)
        self.t1_p.setDecimals(4)
        self.t1_p.setObjectName("t1_p")
        self.gridLayout.addWidget(self.t1_p, 3, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 3, 2, 1, 1)
        self.t2_label_pi = QtWidgets.QLabel(self.tab_2)
        self.t2_label_pi.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2_label_pi.setObjectName("t2_label_pi")
        self.gridLayout_4.addWidget(self.t2_label_pi, 9, 1, 1, 1)
        self.t2_label_mi = QtWidgets.QLabel(self.tab_2)
        self.t2_label_mi.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t2_label_mi.setObjectName("t2_label_mi")
        self.gridLayout_4.addWidget(self.t2_label_mi, 10, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("img/plyn.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 1, 1, 2, 4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem7, 11, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 4, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 5, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 5, 1, 1, 1)
        self.t2_out = QtWidgets.QTextEdit(self.tab_2)
        self.t2_out.setReadOnly(True)
        self.t2_out.setObjectName("t2_out")
        self.gridLayout_4.addWidget(self.t2_out, 4, 4, 6, 1)
        self.t2_calc = QtWidgets.QPushButton(self.tab_2)
        self.t2_calc.setObjectName("t2_calc")
        self.gridLayout_4.addWidget(self.t2_calc, 10, 4, 1, 1)
        self.t2_ok = QtWidgets.QPushButton(self.tab_2)
        self.t2_ok.setAutoDefault(False)
        self.t2_ok.setDefault(True)
        self.t2_ok.setFlat(False)
        self.t2_ok.setObjectName("t2_ok")
        self.gridLayout_4.addWidget(self.t2_ok, 6, 2, 1, 2)
        self.t2_next = QtWidgets.QPushButton(self.tab_2)
        self.t2_next.setObjectName("t2_next")
        self.gridLayout_4.addWidget(self.t2_next, 8, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 4, 5, 1, 1)
        self.t2_mi = QtWidgets.QSpinBox(self.tab_2)
        self.t2_mi.setMaximum(9999)
        self.t2_mi.setObjectName("t2_mi")
        self.gridLayout_4.addWidget(self.t2_mi, 10, 2, 1, 2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem10, 7, 2, 1, 1)
        self.t2_back = QtWidgets.QPushButton(self.tab_2)
        self.t2_back.setObjectName("t2_back")
        self.gridLayout_4.addWidget(self.t2_back, 8, 2, 1, 1)
        self.t2_pi = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.t2_pi.setObjectName("t2_pi")
        self.gridLayout_4.addWidget(self.t2_pi, 9, 2, 1, 2)
        self.t2_k = QtWidgets.QSpinBox(self.tab_2)
        self.t2_k.setMaximum(9999)
        self.t2_k.setObjectName("t2_k")
        self.gridLayout_4.addWidget(self.t2_k, 4, 2, 1, 2)
        self.t2_n = QtWidgets.QSpinBox(self.tab_2)
        self.t2_n.setMaximum(9999)
        self.t2_n.setObjectName("t2_n")
        self.gridLayout_4.addWidget(self.t2_n, 5, 2, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_32 = QtWidgets.QLabel(self.tab_4)
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap("img/lapl.png"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 1, 1, 1, 3)
        self.t3_p = QtWidgets.QDoubleSpinBox(self.tab_4)
        self.t3_p.setDecimals(4)
        self.t3_p.setObjectName("t3_p")
        self.gridLayout_5.addWidget(self.t3_p, 3, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.tab_4)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 4, 1, 1, 1)
        self.t3_m = QtWidgets.QSpinBox(self.tab_4)
        self.t3_m.setMaximum(9999)
        self.t3_m.setObjectName("t3_m")
        self.gridLayout_5.addWidget(self.t3_m, 5, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_4)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 5, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_4)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 3, 1, 1, 1)
        self.t3_calc = QtWidgets.QPushButton(self.tab_4)
        self.t3_calc.setObjectName("t3_calc")
        self.gridLayout_5.addWidget(self.t3_calc, 6, 3, 1, 1)
        self.t3_n = QtWidgets.QSpinBox(self.tab_4)
        self.t3_n.setMaximum(9999)
        self.t3_n.setProperty("value", 0)
        self.t3_n.setObjectName("t3_n")
        self.gridLayout_5.addWidget(self.t3_n, 4, 2, 1, 1)
        self.t3_out = QtWidgets.QTextEdit(self.tab_4)
        self.t3_out.setReadOnly(True)
        self.t3_out.setObjectName("t3_out")
        self.gridLayout_5.addWidget(self.t3_out, 3, 3, 3, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem11, 4, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem12, 7, 3, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem13, 0, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem14, 1, 4, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem15, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "lb3"))
        self.label_4.setText(_translate("MainWindow", "m1:"))
        self.label_5.setText(_translate("MainWindow", "m2:"))
        self.t1_calc.setText(_translate("MainWindow", "Расчитать!"))
        self.t1_calc.setShortcut(_translate("MainWindow", "Return"))
        self.label_2.setText(_translate("MainWindow", "p:"))
        self.label_3.setText(_translate("MainWindow", "m:"))
        self.label.setText(_translate("MainWindow", "n:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Формула Бернулли"))
        self.t2_label_pi.setText(_translate("MainWindow", "p[i]"))
        self.t2_label_mi.setText(_translate("MainWindow", "m[i]"))
        self.label_16.setText(_translate("MainWindow", "k"))
        self.label_17.setText(_translate("MainWindow", "n:"))
        self.t2_calc.setText(_translate("MainWindow", "Расчитать"))
        self.t2_calc.setShortcut(_translate("MainWindow", "Return"))
        self.t2_ok.setText(_translate("MainWindow", "Подтвердить"))
        self.t2_next.setText(_translate("MainWindow", "Следующий"))
        self.t2_next.setShortcut(_translate("MainWindow", "Right"))
        self.t2_back.setText(_translate("MainWindow", "Предыдущий"))
        self.t2_back.setShortcut(_translate("MainWindow", "Left"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Полиномиальная формула"))
        self.label_34.setText(_translate("MainWindow", "n:"))
        self.label_35.setText(_translate("MainWindow", "m:"))
        self.label_33.setText(_translate("MainWindow", "p:"))
        self.t3_calc.setText(_translate("MainWindow", "Расчитать"))
        self.t3_calc.setShortcut(_translate("MainWindow", "Return"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Локальная теорема Муавра-Лапласа"))

